# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy Configuration

on:
  push:
    branches: [main]
    paths:
      - cdk/src/CDK/configuration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          npm install -g aws-cdk
          dotnet tool install -g Amazon.Lambda.Tools
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Deploy to AWS
        run: |
          export STACK_POSTFIX=Dev
          cdk deploy ConfigurationStack --require-approval=never
      - name: Functional tests
        env:
          TEMPORARY_PASSWORD: ${{ secrets.TEMPORARY_PASSWORD }}
        run: |
          export STACK_POSTFIX=Dev
          dotnet test ./tests/Stocks.FunctionalTests/Stocks.FunctionalTests.csproj
      - name: Deploy to AWS Production
        run: |
          export STACK_POSTFIX=Prod
          cdk deploy ConfigurationStack --require-approval=never
      - name: Functional tests
        env:
          TEMPORARY_PASSWORD: ${{ secrets.TEMPORARY_PASSWORD }}
        run: |
          export STACK_POSTFIX=Prod
          dotnet test ./tests/Stocks.FunctionalTests/Stocks.FunctionalTests.csproj